### ISSUE TITLE
PokemonGeneratorConfig: impossible combinations

### ISSUE THREAD

**Issue by HackuJacku** [EnvyWare/API#18]
The PokémonGeneratorConfig is producing impossible combinations. When a combination is generated, they should be checked against each other and the stats to make sure it is possible.

For example: Female Gallade, Gallade can only be male.
![image](https://user-images.githubusercontent.com/18508413/180432223-e7ee662c-2c6f-4dc6-8730-7c6c50f9936b.png)

**Comment by danorris709** [comment]
Fixed for next version

**Comment by HackuJacku** [comment]
Using this release (2.9.1), still an issue 
![image](https://user-images.githubusercontent.com/18508413/180583017-49d4c466-9780-484f-828e-ac2193cc32c9.png)

**Comment by danorris709** [comment]
Pixelmon stat file issue

**Comment by danorris709** [comment]
No, I'm just stupid! (Fixed for next version)
